# Generated by Django 3.0.5 on 2020-04-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorapp', '0002_auto_20200411_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.CharField(blank=True, default='not available', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, default='NOT AVAILABLE', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='NOT AVAILABLE', max_length=20),
        ),
    ]
