# Generated by Django 3.0.5 on 2020-04-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorapp', '0003_auto_20200411_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='not comp', max_length=10),
        ),
    ]
