# Generated by Django 3.0.5 on 2020-04-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorapp', '0004_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(default='not completed', max_length=10),
        ),
    ]
