# Generated by Django 3.0.5 on 2020-04-12 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorapp', '0005_auto_20200412_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
